version: "3.9"

services:

  ads-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV_TYPE=docker
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ads-service
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
