cfg_type: dev
http_server_address: 0.0.0.0:8080

auth_grpc:
  address: auth-server:44044
  secret_key: secret123
  app_id: 1

postgres:
  pg_url: postgres://postgres:postgres@postgres/articles-service?sslmode=disable
  max_connections: 100
  migrations_dir: file://migrations

redis:
  address: redis:6379
  database: 0
  password: 
