version: "3.9"

services:

  articles-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - articles-network
      - service

  postgres:
    image: postgres:16.3                
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=articles-service
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - service

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    networks:
      - service


volumes:
  pgdata:

networks:
  articles-network:
    external: true
  service:

