env: "local"
access_token_ttl: 15m
refresh_token_ttl: 24h
pg_url: postgres://postgres:postgres@localhost:5433/auth-service?sslmode=disable
migrations_path: "./migrations"
grpc:
  port: 44044
  timeout: 10h
